version: '3.8'

services:
  web:
    build: API
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    volumes:
      - files:/files
    env_file:
      - API/.env

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - API/.env

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  cache:
    image: redis:7-alpine
    restart: always
    env_file:
      - API/.env

volumes:
  postgres_data:
  files:
  pgadmin-data:
